# Generated by Django 4.0.4 on 2022-04-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders_orderupdate_remove_product_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='sub_category',
        ),
    ]
