# Generated by Django 4.0.4 on 2022-04-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_subcategory_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.CharField(default='', max_length=111),
        ),
    ]
